### ISSUE TITLE
Segfault with ujson module

### ISSUE THREAD

**Issue by ffix** [micropython/micropython#1097]
I've got a strange segfault on v1.3.9 (ArchLinux):
```
$ micropython -c 'import ujson; ujson.loads("")["test"]'
Segmentation fault (core dumped)
```
There is gdb output:
```
GNU gdb (GDB) 7.8.2
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from micropython...done.
(gdb) run
Starting program: /home/fix/aur/micropython.debug/src/micropython-1.3.9/unix/micropython 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
Micro Python  on 2015-02-02; linux version
>>> import ujson
>>> ujson.loads("")["test"]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000422ddc in mp_obj_get_type (o_in=0x0) at ../py/obj.c:48
48	        return (mp_obj_t)o->type;
(gdb) where
#0  0x0000000000422ddc in mp_obj_get_type (o_in=0x0) at ../py/obj.c:48
#1  0x0000000000423cd8 in mp_obj_subscr (base=0x0, index=0x6ee, value=0x8) at ../py/obj.c:466
#2  0x000000000043d9ee in mp_execute_bytecode (code_state=0x7fffffffcd10, inject_exc=<optimized out>) at ../py/vm.c:370
#3  0x0000000000429063 in fun_bc_call (self_in=0x7ffff7fb2e60, n_args=0, n_kw=0, args=0x0) at ../py/objfun.c:188
#4  0x000000000041fd8e in mp_call_function_n_kw (fun_in=0x7ffff7fb2e60, n_args=0, n_kw=0, args=0x0) at ../py/runtime.c:577
#5  0x000000000041fccb in mp_call_function_0 (fun=0x7ffff7fb2e60) at ../py/runtime.c:551
#6  0x0000000000447809 in execute_from_lexer (lex=0x7ffff7fb2ea0, input_kind=MP_PARSE_SINGLE_INPUT, is_repl=true) at main.c:165
#7  0x00000000004479e6 in do_repl () at main.c:215
#8  0x0000000000448659 in main (argc=1, argv=0x7fffffffe1a8) at main.c:483
(gdb) 
```

**Comment by dpgeorge** [comment]
Should now be fixed.  (Problem was that the empty string was returning a null object.)
