### ISSUE TITLE
Cannot urequests.get(url)

### ISSUE THREAD

**Issue by Mosazghi** [micropython/micropython#11825]
I get the following error whenever i try to use 'urequests'. 

```
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "urequests.py", line 180, in get
  File "urequests.py", line 76, in request
OSError: -202
```

**Comment by dpgeorge** [comment]
Please explain your problem in more detail: which port of MicroPython you use, and the exact command and URL you are attempting to get.

**Comment by Mosazghi** [comment]
```
import time
import urequests

while True:
    req = requests.get("http://10.0.0.13:3000/koordinater")
   
    print(req.json())
    ```
    ESP32 COM4

**Comment by Mosazghi** [comment]
Looks like i had to connect to a wifi for it to work properly
