### ISSUE TITLE
py-core/docs: CPython: Class Level Name Mangling does not happen

### ISSUE THREAD

**Issue by trwbox** [micropython/micropython#12150]
When running some code, I found that MicroPython does not do any [name mangling](https://docs.python.org/3/tutorial/classes.html#private-variables) inside of classes. When trying to find information about it, the only item I found was a [TODO comment](https://github.com/micropython/micropython/blob/70c564324c9a2af323866b0235dba75f534a9926/py/compile.c#L44) from the initial commit of the compiler, and not mention elsewhere. Being such an edge case issue, I'm not sure that implementing it is truly necessary, as most issues that arise from this not happening can be fixed in the Python code itself. However, it should be included in [MicroPython Differences](https://docs.micropython.org/en/latest/genrst/index.html#) page in the docs making it much easier for anyone that encounters it to find the information they need.

Tested on MicroPython device
```txt
MicroPython v1.20.0 on 2023-04-26; Raspberry Pi Pico with RP2040
```

Example Code:
```python
def __example_print(string):
    print(string)

class ExampleClass():
    def __init__(self, string) -> None:
        self.string = string
    def do_print(self):
        __example_print(self.string)

# A simple string for testing
string = 'A testing string'

# Should print the string the first time
__example_print(string)

# Create a new object from the class with the same string
new_object = ExampleClass(string)

# Print a second time by accessing the attribute
__example_print(new_object.string)

# Try to run the do_print() method to print it again.
# This should cause an NameError as '__example_print' should be name mangled to '_ExampleClass__example_print', which does not exist
# However, it does not and prints that string we initialized with for the third time
new_object.do_print()
```

Expected Output:
```txt
A testing string
A testing string
Traceback (most recent call last):
  File "/tmp/example_code.py", line 26, in <module>
    new_object.do_print()
  File "/tmp/example_code.py", line 9, in do_print
    __example_print(self.string)
    ^^^^^^^^^^^^^^^
NameError: name '_ExampleClass__example_print' is not defined
```

Micropython output:
```txt
A testing string
A testing string
A testing string
```

**Comment by dpgeorge** [comment]
We can create a CPython difference test with the above code.  Then it will appear in the docs.

@trwbox would you like to make a PR for that?  I suggest putting the code in `tests/cpydiff/core_class_name_mangling.py`.

**Comment by agatti** [comment]
This was addressed by 3deeabe6e87d893196227b41ca997d78783ab14c, closing as completed.
