### ISSUE TITLE
ESP32-S3 umqtt  Error info:

### ISSUE THREAD

**Issue by BlackCattleProgrammer996** [micropython/micropython#13269]
MicroPython的工程师你好!  非常感谢你们开发了MicroPython ,让我们嵌入式芯片多了更多的选择 , 接下来我向你描述我遇到的问题:
1. 我的硬件设备是ESP32-S3, 当我在代码中 from umqtt.robust import MQTTClient  , 
我发现ESP32-S3如果连接阿里云的MQTT服务器( MQTT服务器地址: mqtt-cn-9lb35537z01.mqtt.aliyuncs.com )就会报错 , 
如果ESP32-S3连接其他MQTT服务器( 比如 本地MQTT服务器: 192.168.43.91 )  就可以正常连接,并且不会报错

然后就会报错:
Traceback (most recent call last):
  File "<stdin>", line 168, in <module>
  File "umqtt/simple.py", line 108, in connect
IndexError: bytes index out of range

我根据这个错误信息去找到报错的代码:
umqtt/simple.py:

        resp = self.sock.read(4)
        assert resp[0] == 0x20 and resp[1] == 0x02
        if resp[3] != 0:
            raise MQTTException(resp[3])
        return resp[2] & 1
        
当我连接到阿里云MQTT服务器时, resp的值是NULL , 所以报错了 ; 但是如果连接本地MQTT服务器 resp 不为NULL

**Comment by BlackCattleProgrammer996** [comment]
我补充一下说明, 我使用一些MQTT客户端工具是可以连接到阿里云MQTT服务器的 , 比如MQTT.fx软件

**Comment by BlackCattleProgrammer996** [comment]
我最近又尝试用umqtt去连接了一些MQTT服务器 发现都是可以的,  连接成功的时候 resp = self.sock.read(4) , resp结果不为None ; 但是我连接 部署在阿里云服务器上的MQTT服务器时, resp = self.sock.read(4)  , resp就是None , 然后报错,导致无法连接; 
我怀疑了ESP32的网络问题, 我写了一个ping方法, 执行MQTT连接之前 , 我首先使用了ping方法去 ping 服务器地址, 发现能够打印ping返回的数据, 这说明 网络链路是正常的, 但是执行  resp = self.sock.read(4) 的时候, resp却没有任何消息

**Comment by BlackCattleProgrammer996** [comment]
如果umqtt无法解决,那么下面这两个库是否可以解决我所描述的问题

比如使用 umqtt.robust2:  [micropython-umqtt.robust2/src/umqtt/robust2.py at master · fizista/micropython-umqtt.robust2 (github.com)](https://github.com/fizista/micropython-umqtt.robust2/blob/master/src/umqtt/robust2.py)

或者使用MicroPython- Mqtt : [peterhinch/micropython-mqtt: A 'resilient' asynchronous MQTT driver. Plus a means of using an ESP8266 to bring MQTT to non-networked targets. (github.com)](https://github.com/peterhinch/micropython-mqtt)
