### ISSUE TITLE
ESP32-S3-Zero(S3FH4R2) - showing flash_size = 0

### ISSUE THREAD

**Issue by alexphobby** [micropython/micropython#13723]
I have the ESP32-S3-Zero(S3FH4R2) module, after flashing from Thonny or esptool, i cannot upload files on it. However i ca use pins and internal libraries(have tested the neopixel onboard). All boards behave the same

import esp
esp.flash_size()
0

also on restart:
MPY: soft reboot
Traceback (most recent call last):
  File "_boot.py", line 11, in <module>
  File "inisetup.py", line 38, in setup
  File "inisetup.py", line 7, in check_bootsec
OSError: (-24579, 'ESP_ERR_FLASH_NOT_INITIALISED')
MicroPython v1.22.1 on 2024-01-05; Generic ESP32S3 module with ESP32S3

python -u -m esptool --port COM34 --chip esp32s3 --baud 115200 erase_flash
python -u -m esptool --port COM34 --chip esp32s3 --baud 115200 write_flash -z 0 ESP32_GENERIC_S3-20240105-v1.22.1.bin

esptool.py v4.7.0
...
Chip is ESP32-S3 (QFN56) (revision v0.2)
Features: WiFi, BLE, Embedded Flash 4MB (XMC), Embedded PSRAM 2MB (AP_3v3)
...
Flash will be erased from 0x00000000 to 0x0018dfff...
Compressed 1628240 bytes to 1066973...
Wrote 1628240 bytes (1066973 compressed) at 0x00000000 in 15.1 seconds (effective 862.7 kbit/s)...
Hash of data verified.

Please advise

**Comment by alexphobby** [comment]
I have finally managed to make it work, will come back with the image and details. 
It is a wonder that the c3 worked out of the box, and s3 was such a pain.

**Comment by alexphobby** [comment]
Here it is:
https://github.com/alexphobby/Micropython/tree/main/ESP32/ESP32_S3_Zero

**Comment by alexphobby** [comment]
Linked instructions to build and also image
