### ISSUE TITLE
Assignment expression raises error if updating global variable

### ISSUE THREAD

**Issue by rkompass** [micropython/micropython#14376]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

w600, RP2, others

### MicroPython version

MicroPython v1.23.0-preview.362.g3995158d9.dirty on 2024-04-19

### Reproduction

a=0; print([(a:=a+1) for b in range(10)])

### Expected behaviour

Expected:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Observed behaviour

Observed:
SyntaxError: identifier redefined as global

### Additional Information

I saw the discussion on [https://github.com/micropython/micropython/pull/4908](https://github.com/micropython/micropython/pull/4908)
but there it is about a variable created in the comprehension context being available as global outside.

Here is a variable already present as global.

**Comment by Gadgetoid** [comment]
Similarly weird case:

CPython 3.12.2:

```
>>> global a; a=0; print([(a:=a+1) for b in range(10)])
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

MicroPython (UNIX standard):

```
>>> global a; a=0; print([(a:=a+1) for b in range(10)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
NameError: local variable referenced before assignment
```
