### ISSUE TITLE
Pico W:when I try "wlan.connect()" and "wlan.scan()" ,I get an "OSError: [Errno 1] EPERM"

### ISSUE THREAD

**Issue by letr007** [micropython/micropython#14408]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) matching this bug, and didn't find any.

### Port, board and/or hardware

raspberry pico w with rp2040

### MicroPython version

MicroPython v1.19.1-88-g74e33e714 on 2022-06-30; Raspberry Pi Pico W with RP2040

### Reproduction

```python
import network

wlan = network.WLAN(network.STA_IF)
wlan.active(True)
wlan.connect(BSSID, pwd)
```

### Observed behaviour

Traceback (most recent call last):
  File "<stdin>", line 169, in handle_key
  File "<stdin>", line 152, in menu_wifi
  File "<stdin>", line 120, in wlan_connect
OSError: [Errno 1] EPERM

### Additional Information

I've looked for a solution to a similar problem, but it doesn't help me.
I tried "micropython.alloc_emergency_exception_buf(100)" by ChatGPT, but it didn't work.

**Comment by letr007** [comment]
After debugging, it was found that it was caused by a WIFI module error
