### ISSUE TITLE
Cryptolib throws ValueError

### ISSUE THREAD

**Issue by jakobzudrell** [micropython/micropython#15185]
### Port, board and/or hardware

rp2

### MicroPython version

MicroPython v1.22.2 on 2024-02-22; Raspberry Pi Pico W with RP2040
MicroPython v1.24.0-preview.11.g1705bc52a on 2024-06-01; Raspberry Pi Pico with RP2040

### Reproduction

```Python
cipher = cryptolib.aes(ubinascii.unhexlify(key), 6, iv)
```

### Expected behaviour

A working AES instance

### Observed behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 34, in <module>
  File "<stdin>", line 20, in main
ValueError: mode
```

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

**Comment by felixdoerre** [comment]
Counter mode is guarded behind a preprocessor macro which is not enabled by default for the rp2 firmware: https://github.com/micropython/micropython/blob/master/extmod/modcryptolib.c#L222
