### ISSUE TITLE
Unix: async iterators appear not to work.

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2721]
The code below, adapted from the example in PEP492 to provide a working fetch_data() method, runs in CPython 3.5.2 but produces this outcome under MicroPython:
```
$ upython 
MicroPython v1.8.1-1042-g05aebb9-dirty on 2016-12-25; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import async_iter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "async_iter.py", line 35, in <module>
  File "/home/adminpete/.micropython/lib/uasyncio/core.py", line 127, in run_until_complete
  File "/home/adminpete/.micropython/lib/uasyncio/core.py", line 119, in run_forever
  File "/home/adminpete/.micropython/lib/uasyncio/core.py", line 81, in run_forever
  File "/home/adminpete/.micropython/lib/uasyncio/core.py", line 124, in _run_and_stop
  File "async_iter.py", line 31, in run
TypeError: 'AsyncIterable' object is not iterable
>>> 
```
Code:
```python
try:
    import asyncio
except ImportError:
    import uasyncio as asyncio

class AsyncIterable:
    def __init__(self):
        self.data = (1, 2, 3, 4, 5)
        self.index = 0

    def __aiter__(self):
        return self

    async def __anext__(self):
        data = await self.fetch_data()
        if data:
            return data
        else:
            raise StopAsyncIteration

    async def fetch_data(self):
        await asyncio.sleep(0.1)
        if self.index >= len(self.data):
            return None
        x = self.data[self.index]
        self.index += 1
        return x

async def run():
    ai = AsyncIterable()
    async for x in ai:
        print(x)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

**Comment by peterhinch** [comment]
Apologies. I've now discovered that the example code in PEP492 is incorrect and the syntax was modified on acceptance of the PEP. The line
```python
    def __aiter__(self):
        return self
```
should read
```python
    async def __aiter__(self):
        return self
```
The example now runs under CPython and MicroPython.
