### ISSUE TITLE
lcd160cr.py get_pixel method fails

### ISSUE THREAD

**Issue by peterhinch** [micropython/micropython#2880]
```python
import lcd160cr

lcd = lcd160cr.LCD160CR('X')
lcd.set_orient(lcd160cr.PORTRAIT)
lcd.get_pixel(0,0)
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "lcd160cr.py", line 246, in get_pixel
TypeError: function takes 6 positional arguments but 5 were given
>>> 
```
the _fcmd2b method requires at least 6 args. Appears fixed by amending the definition with ``a3=0`.

**Comment by dpgeorge** [comment]
Thanks for the report, get_pixel() was obviously not well tested :).  Now fixed, see above.
