### ISSUE TITLE
ESP8266 'module' object has no attribute 'VfsFat'

### ISSUE THREAD

**Issue by pdxjohnny** [micropython/micropython#3019]
Steps to reproduce:

```
wget http://micropython.org/resources/firmware/esp8266-512k-20170413-v1.8.7-616-gc7e8c6f.bin
esptool.py --port /dev/ttyUSB0 erase_flash
esptool.py --port /dev/ttyUSB0 --baud 460800 write_flash --flash_size=detect 0 esp8266-512k-20170413-v1.8.7-616-gc7e8c6f.bin
picocom /dev/ttyUSB0 -b115200
```

Output after hitting reset pin (on adafruit Feather HUZZAH)
```
... garbage ...

Traceback (most recent call last):
  File "_boot.py", line 13, in <module>
  File "_boot.py", line 8, in <module>
AttributeError: 'module' object has no attribute 'VfsFat'
OSError: [Errno 2] ENOENT
OSError: [Errno 2] ENOENT

MicroPython v1.8.7-616-gc7e8c6f on 2017-04-13; ESP module with ESP8266
Type "help()" for more information.
>>> import os
>>> os.listdir('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'listdir'
>>>
```

I'm debugging this now but wanted to let others know it is an issue. Probably related to #1947

**Comment by pdxjohnny** [comment]
uos does indeed contain no `VfsFat`.

```
>>> uos.
__name__        uname           urandom         dupterm
dupterm_notify
```

_boot.py: https://github.com/micropython/micropython/blob/4f29b315a6900445d2139652914f81168763816f/esp8266/modules/_boot.py

```

import gc
gc.threshold((gc.mem_free() + gc.mem_alloc()) // 4)
import uos
from flashbdev import bdev

try:
    if bdev:
        vfs = uos.VfsFat(bdev)
        uos.mount(vfs, '/flash')
        uos.chdir('/flash')
except OSError:
    import inisetup
    vfs = inisetup.setup()

gc.collect()
```

**Comment by pdxjohnny** [comment]
Ok I'm just stupid but the reason I created this issue was so that others be able to google and find the answer. Which is that one should not use the 512k versions if you want the FS. Use the OTA or the stable.

**Comment by pdxjohnny** [comment]
Props to @pfalcon for updating documentation about this so quick :1st_place_medal:
