### ISSUE TITLE
An error occured when input : " import webrepl_setup "

### ISSUE THREAD

**Issue by chineserain** [micropython/micropython#3330]
wrong notice

```
import webrepl_setup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "webrepl_setup.py", line 111, in <module>
  File "webrepl_setup.py", line 80, in main
  File "webrepl_setup.py", line 49, in get_daemon_status
OSError: [Errno 2] ENOENT

```

**Comment by dpgeorge** [comment]
Most likely you don't have a boot.py file in your filesystem.  Either create an empty one or do a complete reinstall of MicroPython.

**Comment by anacrolix** [comment]
Bummer, any chance of just making this file or ignoring it instead? Should I just make a PR?
