### ISSUE TITLE
ESP32: OSError: 128

### ISSUE THREAD

**Issue by Lisa999** [micropython/micropython#3513]
Running on a ESP32 Lolin32 Lite:
>> import upyeasy_wifi_test
Starting uPyEasy Webserver test...
I (32758) network: event 1
SSID: TALKTALK65AFF2 Channel: 11 Strength: -28 Security type: 0
Trying to connect to AP: TALKTALK65AFF2
Bind address info: [(2, 1, 0, '192.168.1.9', ('192.168.1.9', 80))]
Listening, connect your browser to http://<this_host>:80/
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "upyeasy_wifi_test.py", line 75, in <module>
File "upyeasy_wifi_test.py", line 57, in main
OSError: 128
>>> 

What's OSError 128? Can't find an explanation what that is anywhere. It explodes on this line: sock, addr = s.accept()
It seems to be a socket related error, simular to issue #1896. But it also happens straight after a hard reset.
Script used attached...
[upyeasy_wifi_test.zip](https://github.com/micropython/micropython/files/1594915/upyeasy_wifi_test.zip)

**Comment by Lisa999** [comment]
Any port above 8000 is working, work-around available. Closing issue...
