### ISSUE TITLE
DHT22 no result

### ISSUE THREAD

**Issue by ds2k5** [micropython/micropython#3593]
Hello,
try to get Temprature from a DHT22

Board: NodeMcu V3, ESP8266
Board      DHT22
GND -->  right (4)
V3 -->      left (1)
PIN4 -->  Signal (2)

found this CODE but did not get a result:

```
import dht
import machine
import time

print("Starting DHT22.")
d = dht.DHT22(machine.Pin(4))

while True:
    print("Measuring.")
    
    retry = 0
    while retry < 3:
        try:
            d.measure()
            break
        except:
            retry = retry + 1
            print(".", end = "")

    print("")

    if retry < 3:
        print("Temperature: %3.1f °C" % d.temperature())
        print("   Humidity: %3.1f %% RH" % d.humidity())

    time.sleep(5)

Starting DHT22.                                                                 
Measuring.                                                                      
...                                                                             
Measuring.                                                                      
...         

```

**Comment by chrisb2** [comment]
According the [datasheet](https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf), see section 6; "When power is supplied to sensor, don't send any instruction to the sensor within one second to pass unstable status", perhaps this is the cause of the issue?

regards,
Chris

**Comment by ds2k5** [comment]
Thanks Chris,
but got error with your CODE
```

paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== from machine import Pin
=== from utime import sleep_ms
=== import dht
=== 
=== sleep_ms(1000)
=== 
=== sensor = dht.DHT22(Pin(4))
=== while True:
===     sensor.measure()
===     print("%0.fC, %0.f%%" % (sensor.temperature(), sensor.humidity()))
===     sleep_ms(1000)
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "dht.py", line 13, in measure
OSError: [Errno 110] ETIMEDOUT

```

**Comment by ds2k5** [comment]
Is it possible to see if a sensor: dht-22 connected ?

from machine import Pin
import onewire
ow = onewire.OneWire(Pin(4))
ow.scan()   

Output: []
