### ISSUE TITLE
Error to define display in esp8266(wemosD1)

### ISSUE THREAD

**Issue by bergpb** [micropython/micropython#3853]
>>> display = ssd1306.SSD1306_I2C(64, 48, i2c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ssd1306.py", line 99, in __init__
  File "ssd1306.py", line 36, in __init__
  File "ssd1306.py", line 61, in init_display
  File "ssd1306.py", line 104, in write_cmd
OSError: [Errno 110] ETIMEDOUT

**Comment by peterhinch** [comment]
This is the MicroPython bug tracker - your problem will be seen by more people and get a faster response in [the forum](https://forum.micropython.org/). If people are to help they will need more details: how your display is connected to the ESP8266 and your code, including I2C initialisation.
