### ISSUE TITLE
Exception chaining not implemented

### ISSUE THREAD

**Issue by pfalcon** [micropython/micropython#391]
This is mostly for tracking differences from CPython.

Also, can discuss if we need this.

Doc: http://legacy.python.org/dev/peps/pep-3134/

Roughly, raising a _new_ exception (not reraising) when we handle another exception, chains them. But CPython prints them not like Java, but upside down:

```
Traceback (most recent call last):
  File "try-reraise3.py", line 5, in <module>
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try-reraise3.py", line 7, in <module>
    raise TypeError
TypeError
```

(But I guess Python prints traceback in reverse order comparing to java either, so the above behavior would be "natural" (the "most important" info printed last)).

**Comment by dpgeorge** [comment]
Closing due to inactivity.

**Comment by dhalbert** [comment]
@jepler implemented exception chaining in CircuitPython: https://github.com/adafruit/circuitpython/pull/7069.
