### ISSUE TITLE
socket connect cause reboot using hostname which cannot be resolved

### ISSUE THREAD

**Issue by nedoskiv** [micropython/micropython#4441]
Hello,
Sorry for bad english.
 I have tried on both available firmwares for esp32 (stable/dev), this code reboots the board if there is no IP address assigned to the board and try to connect using socket 

```
MicroPython v1.10 on 2019-01-25; ESP32 module with ESP32
Type "help()" for more information.
>>> client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'socket' isn't defined
>>> import usocket as socket
[0;32mI (114896) modsocket: Initializing[0m
>>> client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> server_address = ('r-control.eu', 80)
>>> client_socket.connect(server_address)
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400f2344  PS      : 0x00060430  A0      : 0x800df730  A1      : 0x3ffc7a80  
A2      : 0x3ffe6250  A3      : 0x3ffbeb20  A4      : 0x00000000  A5      : 0x0000f3a9  
A6      : 0x00000022  A7      : 0xfffffffe  A8      : 0x00000000  A9      : 0x3ffc7a60  
A10     : 0x00000038  A11     : 0x3ffc7a80  A12     : 0x00000002  A13     : 0x00000002  
A14     : 0x0000002a  A15     : 0x3ffc7c20  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000014  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x400f2344:0x3ffc7a80 0x400df72d:0x3ffc7ab0 0x400dbb25:0x3ffc7ad0 0x400dbb8d:0x3ffc7af0 0x400e8cf5:0x3ffc7b10 0x400df848:0x3ffc7bb0 0x400dbb25:0x3ffc7c20 0x400dbb52:0x3ffc7c40 0x400f6e76:0x3ffc7c60 0x400f70c0:0x3ffc7d00 0x400efacc:0x3ffc7d40

Rebooting...
```

Further testing indicate that if IP address is used instead of hostname, it do not fail that way - raise exception:

```
>>> import usocket as socket
[0;32mI (308863) modsocket: Initializing[0m
>>> client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> server_address = ('10.10.10.10', 80)
>>> client_socket.connect(server_address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 118


```

Furthermore , it cause reboot even if you have internet connection and try to connect to hostname that cannot be resolved.

**Comment by dpgeorge** [comment]
Thanks for the report.  All the above crashes should be fixed by dadee5fa2497807dbf3ce33e2432bc4bf39b4937
