### ISSUE TITLE
Pyboard-D Latest Build - ordinal not in range(128)

### ISSUE THREAD

**Issue by pacmac** [micropython/micropython#4690]
ubuntu 18.04LTS

```
make -j6 BOARD=PYBD_SF2
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: Warning: File 'mpconfigport.mk' has modification time 0.32 s in the future
GEN build-PYBD_SF2/genhdr/moduledefs.h
../../py/py.mk:346: recipe for target 'build-PYBD_SF2/genhdr/moduledefs.h' failed
Traceback (most recent call last):
  File "../../py/makemoduledefs.py", line 107, in <module>
    main()
  File "../../py/makemoduledefs.py", line 101, in main
    modules |= find_module_registrations(c_file)
  File "../../py/makemoduledefs.py", line 53, in find_module_registrations
    return set(re.findall(pattern, c_file_obj.read()))
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10887: ordinal not in range(128)
make: *** [build-PYBD_SF2/genhdr/moduledefs.h] Error 1
make: *** Deleting file 'build-PYBD_SF2/genhdr/moduledefs.h'
```

**Comment by pacmac** [comment]
Also, the main micropython repo fails to build for PBBOARD 1.1.

However ESP8266, ESP32 and NRF all build successfully for me.

**Comment by dpgeorge** [comment]
It should now build fine.

**Comment by pacmac** [comment]
SF2, SF6, ESP8266, ESP32 and NRF all build successfully

Thanks
