### ISSUE TITLE
ESP32 - First time building micropython - Help 2

### ISSUE THREAD

**Issue by ShanmugaCA** [micropython/micropython#5277]
Hi,

This is in continuation of the "ESP32 - First time building micropython - Help #5269".
After creating the venv, unable to successfully execute the make for ESP32. Any help is appreciated.

*  The make submodules is success, no errors, here is the O/p:
/micpyth/micropython/ports/esp32$ make submodules
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Building with ESP IDF v4
Updating submodules: lib/berkeley-db-1.xx 

* Where as the make failed with multiple errors, here are the errors:

(venv) shanmuganathan@GHHPS3X2E:~/esp/micpyth/micropython/ports/esp32$ make
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Building with ESP IDF v4
GEN build-GENERIC/sdkconfig.h
Traceback (most recent call last):
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1128, in _open
    return open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '~/esp/micpyth/micropython/ports/esp32/esp-idf/components/bt/host/bluedroid/Kconfig.in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1158, in _enter_file
    self._file = self._open(filename)
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1149, in _open
    '"{}"'.format(self.srctree)))
OSError: Could not open '~/esp/micpyth/micropython/ports/esp32/esp-idf/components/bt/host/bluedroid/Kconfig.in' (ENOENT: No such file or directory). Perhaps the $srctree environment variable (which was unset) is set incorrectly. Note that the current value of $srctree is saved when the Kconfig instance is created (for consistency and to cleanly separate instances).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/confgen.py", line 548, in <module>
    main()
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/confgen.py", line 221, in main
    config = kconfiglib.Kconfig(args.kconfig)
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 656, in __init__
    self.top_node)  # prev_node
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1636, in _parse_block
    node)         # prev_node
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1587, in _parse_block
    prev_node)
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1636, in _parse_block
    node)         # prev_node
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1636, in _parse_block
    node)         # prev_node
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1583, in _parse_block
    self._enter_file(sourced_file)
  File "/home/shanmuganathan/esp/micpyth/micropython/ports/esp32/esp-idf/tools/kconfig_new/kconfiglib.py", line 1167, in _enter_file
    .format(self._filename, self._linenr, e.message))
AttributeError: 'OSError' object has no attribute 'message'
Makefile:380: recipe for target 'build-GENERIC/sdkconfig.h' failed
make: *** [build-GENERIC/sdkconfig.h] Error 1

Any clue ? 
Where i am missing ?

Please help

thanks
Shanmuganathan

**Comment by jimmo** [comment]
I think this might be because you're using `~` to specify the IDF path -- see the note in the README.md:

```Be sure to enter the correct path to your local copy of the IDF repository (and use $(HOME), not tilde, to reference your home directory).```

These sorts of questions are perhaps better asked on the forum -- see https://forum.micropython.org/ . This issue tracker is for raising bugs against MicroPython.
