### ISSUE TITLE
Native modules don't compile on macOS for x64 / x86 arch

### ISSUE THREAD

**Issue by stepansnigirev** [micropython/micropython#5500]
I tried to compile the native module example (`examples/natmod/feature0`) on macOS and got the following error:

```
GEN build/features0.config.h
CC features0.c
LINK build/features0.o
Traceback (most recent call last):
  File "../../../tools/mpy_ld.py", line 964, in <module>
    main()
  File "../../../tools/mpy_ld.py", line 961, in main
    do_link(args)
  File "../../../tools/mpy_ld.py", line 937, in do_link
    load_object_file(env, file)
  File "../../../tools/mpy_ld.py", line 585, in load_object_file
    elf = elffile.ELFFile(f)
  File "/usr/local/lib/python3.7/site-packages/elftools/elf/elffile.py", line 67, in __init__
    self._identify_file()
  File "/usr/local/lib/python3.7/site-packages/elftools/elf/elffile.py", line 421, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/usr/local/lib/python3.7/site-packages/elftools/common/utils.py", line 77, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/usr/local/lib/python3.7/site-packages/elftools/common/utils.py", line 109, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Magic number does not match
make: *** [build/features0.native.mpy] Error 1
```

On Ubuntu everything compiles. On Mac armv7m works, x86 and x64 - not.
I am using macOS Catalina v10.15.2.

**Comment by dpgeorge** [comment]
> On Mac armv7m works, x86 and x64 - not.

I guess that the host linker on Mac (clang?) is producing an ELF that elftools does not recognise.  Try running `make V=1` to get full output and post it here.

**Comment by stepansnigirev** [comment]
Here it is:
```
/bin/mkdir -p build
GEN build/features0.config.h
python3 ../../../tools/mpy_ld.py '-vvv' --arch x64 --preprocess -o build/features0.config.h features0.c
CC features0.c
gcc -I. -I../../.. -std=c99 -Os -Wall -Werror -DNDEBUG -DNO_QSTR -DMP_CONFIGFILE='<build/features0.config.h>' -fpic -fno-common -U _FORTIFY_SOURCE  -fno-stack-protector -DMICROPY_FLOAT_IMPL=MICROPY_FLOAT_IMPL_DOUBLE  -o build/features0.o -c features0.c
LINK build/features0.o
python3 ../../../tools/mpy_ld.py '-vvv' --arch x64 --qstrs build/features0.config.h -o build/features0.native.mpy build/features0.o
qstr vals: factorial
qstr objs: 
Traceback (most recent call last):
  File "../../../tools/mpy_ld.py", line 964, in <module>
    main()
  File "../../../tools/mpy_ld.py", line 961, in main
    do_link(args)
  File "../../../tools/mpy_ld.py", line 937, in do_link
    load_object_file(env, file)
  File "../../../tools/mpy_ld.py", line 585, in load_object_file
    elf = elffile.ELFFile(f)
  File "/usr/local/lib/python3.7/site-packages/elftools/elf/elffile.py", line 67, in __init__
    self._identify_file()
  File "/usr/local/lib/python3.7/site-packages/elftools/elf/elffile.py", line 421, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/usr/local/lib/python3.7/site-packages/elftools/common/utils.py", line 77, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/usr/local/lib/python3.7/site-packages/elftools/common/utils.py", line 109, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Magic number does not match
make: *** [build/features0.native.mpy] Error 1
```

**Comment by dpgeorge** [comment]
So the problem is that gcc (=clang) is generating Mach-O files, but `mpy_ld.py` only supports ELF files.  Maybe `mpy_ld.py` will support Mach-O files one day, but for now a way to get it working would be to install a C cross compiler that can emit ELF files on Mac.

**Comment by stepansnigirev** [comment]
I see. Thank you! I will keep using my linux machine for now then.

**Comment by jonnor** [comment]
Does anyone have a tip for how to install a cross-compiler that can output ELF on Mac OS?

And would one actually be able to load such files as native modules on Mac OS?

**Comment by agatti** [comment]
> Does anyone have a tip for how to install a cross-compiler that can output ELF on Mac OS?

Assuming you want to target Apple M-family machines you can install homebrew's [aarch64-elf-gcc](https://formulae.brew.sh/formula/aarch64-elf-gcc) and [aarch64-elf-binutils](https://formulae.brew.sh/formula/aarch64-elf-binutils) packages.  For older intel machines there's [i686-elf-gcc](https://formulae.brew.sh/formula/i686-elf-gcc) and [i686-elf-binutils](https://formulae.brew.sh/formula/i686-elf-binutils).

> And would one actually be able to load such files as native modules on Mac OS?

For Intel, I guess things should more or less work as they are, probably you may need to play a bit with configuration definitions and see if the ABI's registers usage matches what the x86/x64 support expects.

For Arm, you'd have to first replicate 1b92bda5b8e5e2db8e57c4b7134930e52bc5207a for AArch64, and #18366 should be merged in (or something like that, so it won't break the debug emitter even further).

Then I guess it's a matter of setting up the right defines and the usual build stuff.  In theory the Unix port's MPY file support could still work on macOS, `mp_unix_alloc_exec` looks like it should support macOS (I see mentions of the `__MACH__` define in there).  If not, that's where the fun part begins :)

For bonus points you could also add AArch64 support to the QEMU port and extend the Unix port's QEMU-based foreign arch tests to also run for AArch64.

Unfortunately I don't have such a machine, otherwise I might have given that a try.

**Comment by jonnor** [comment]
Hi @agatti and thanks for great pointers. I do not have a Mac machine either, so I will not be pursuing this myself either. But hopefully this will be enough for someone who has/uses a Mac to be able to test/debug/fix.
I do run Mac OS in CI for emlearn-micropython tests, so if someone does come up with a working thing, I would be happy to test/verify it.

**Comment by agatti** [comment]
Getting back on this, the situation is a bit more complex and it turns out a paragraph got accidentally deleted, and I've looked a bit more into this and found out there is some more stuff to be done for AArch64 :(

What is left to do besides what I mentioned earlier:

* Add an entry in the ifeq/else block in `py/dynruntime.mk` to handle the `ARCH` parameter in natmods' makefile
* Add support in `tools/mpy_ld.py` for any additional relocation types that have been added by Arm to support 64 bit ELF files
* Let `sys.implementation._mpy` know you're running on Aarch64 with something like [1]
* Add AArch64 to `MP_NATIVE_ARCH_NAMES` in `tools/mpy-tool.py`
* Add AArch64 to `AVAILABLE_ARCHS` in `tests/run-natmodtests.py`
* Update the relevant documentation.

~~At this point you'd expect it's just a matter of enabling `MICROPY_PERSISTENT_CODE_LOAD` and being done with it, but sadly it's not.~~

~~Natmod loading right now is tightly coupled with the presence of a native emitter.  You can look at `load_raw_code` in `py/persistentcode.c`, `MICROPY_PERSISTENT_CODE_LOAD` gets you there, but then if you don't have a native emitter enabled all the various checks stop you in your tracks.  Until very recently there were no architectures without a native emitter, and now that there's one (RV64) there's no code loading support enabled for it anyway.~~

~~That said, unless I'm missing something it might be possible to let code loading work without the presence of a native emitter.  That's also what stops RV64 from gaining natmod support, all that was needed to add to `tools/mpy_ld.py` to have all example natmods build was a handful of lines anyway [2].~~

**Edit:** I've been nerd-sniped, again.  The natmod loader changes are part of #18428, so the difficult part left for this is the AArch64 relocations support in `tools/mpy_ld.py`.  You can easily adapt the rest of the changes in that PR that do not mess with the QEMU port and replace RV64IMC with something more appropriate.

[1]
```diff
--- i/py/persistentcode.h
+++ w/py/persistentcode.h
@@ -73,6 +73,8 @@
     #define MPY_FEATURE_ARCH (MP_NATIVE_ARCH_XTENSAWIN)
 #elif MICROPY_EMIT_RV32
     #define MPY_FEATURE_ARCH (MP_NATIVE_ARCH_RV32IMC)
+#elif MICROPY_PERSISTENT_CODE_LOAD && defined(__ARM_ARCH) && defined(__ARM_ARCH_ISA_A64)
+    #define MPY_FEATURE_ARCH (MP_NATIVE_ARCH_AARCH64)
 #else
     #define MPY_FEATURE_ARCH (MP_NATIVE_ARCH_NONE)
 #endif
```

**Comment by agatti** [comment]
This should have been addressed with #18667 (32-bits, `i686-elf-gcc` and `i686-elf-binutils` Homebrew packages) and #19437 (64-bits, `x86_64-elf-gcc` and `x86_64-elf-binutils` Homebrew packages).

Closing this as completed, feel free to reopen if you think the issue was not solved by those two PRs.
