### ISSUE TITLE
Support for STM32H750 Value line ?

### ISSUE THREAD

**Issue by mtk11** [micropython/micropython#6784]
STH32H750 is quite fast MCU - running up to 480 MHz, however the internal Flash memory is just 128kB. STM32H7Cube has some example how to execute in place from QSPI, but ST used some not common flash chip – mt25tl01g as well as this approach requires writing a new STM32CubeProg driver.

Wondered if it might be more convenient to have the XIP execution integrated in Micropython and have the core Micropython on the integrated flash while loading the needed libraries dynamically ?

**Comment by mtk11** [comment]
Found today an interesting comment on github stating that the actually FLASH size of STM32H750 is 2MB and decided to test it. STM32 ST-LINK Utility does not allow to write hex files bigger than the specified by the manufacturer. However when converted the hex to bin, I was able to write micropython to the FLASH. The result (STM32H750 @ 400 MHz):

Pystone(1.2) time for 500 passes = 91ms
This machine benchmarks at 5494 pystones/second

Quite decent result for a MCU that can be purchased for 3 USD on Taobao, of course if actually DHL delivers it, but that is another topic.

There is an issue with the SWD interface, after programming the chip, the interface is no more accessible. I did specified in:

mpconfigboard.h

// SWD interface
#define MICROPY_HW_SWDIO            (pin_PA13)
#define MICROPY_HW_SWDCLK           (pin_PA14)

pins.csv

SWDIO,PA13
SWDCLK,PA14

Any additional required settings ?

**Comment by mtk11** [comment]
Decided to use an external QSPI flash – Winbond 25Q128FV, but some very strange issues appeared. When copy a file, let say [pystone_lowmem.py](https://raw.githubusercontent.com/micropython/micropython-lib/master/pystone_lowmem/pystone_lowmem.py), via the USB MSC class, the file gets corrupted at:

line 58: self.StringComp = St&–жt6цЧ  ….
line 140: IntParOut = InE##$ ….

If transfer the file via the UART (not USB CDC driver), the file is shown correctly when loaded via USB MSC, but when try to import the file:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pystone_lowmem1.py", line 226
SyntaxError: invalid syntax

the second time, it loads, but when try to execute the main:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'main'

If try to read the file with file.read():

line 226: 
for IntInde\x06\x02\x07&\x16\x06vR\x07D\x06\x062\x02\x04\x07D\x06\x062"\u0422\x02\x02\x02\x02\x02\x02\x02\x04\x17\'&\x17%\x06\x17%\x07D\x06\x062\x02\x02\x02\x03%\

@ 200 MHz main frequency:
for IntInde\x06\x02\x07&\x16\x06vR\x07D\x06\x062\x02\x04\x07D\x06\x062"\u0422\x02\x02\x02\x02\x02\x02\x02\x04\x17\'&\x17%\x06\x17%\x07D\x06\x062\x02\x02\x02\x03%\U00015d16\x07D\x06FW\x02\

I tried different chip W25Q64, settings in qspi.c, decreasing the MCU speed noting works. And the corrupted data looks repeatable. 

Any suggestions ?

Another problem I am facing is with the ADC. I get some strange readings. I have connected the int DAC to an ADC input. Setting the DAC output to let say: 0.439 V (34), When read once the ADC, get a value: 8770, if continuously read, 1024 time, get the following:

![adc1](https://user-images.githubusercontent.com/73300694/106449616-d19f2900-648c-11eb-8d44-29ccab200a35.jpg)

Setting the DAC to 1.638 V, 128 (by the way shouldn’t be the DAC implementation be 12-bit), produces:

![adc2](https://user-images.githubusercontent.com/73300694/106449756-fbf0e680-648c-11eb-904c-7d2f7566af99.jpg)

Anyone experienced such issues with the STM32H7xx series ?
