### ISSUE TITLE
rp2: usasyncio: sys.stdout not working

### ISSUE THREAD

**Issue by zsquareplusc** [micropython/micropython#6978]
the Pico port does not have a separate USB_VCP object so we resort to use `sys` stdio. while receiving works, transmitting blocks or crashes on writing. other ports like the pyboard support this. It would be good if this works so that `uasyncio` communication can be done via USB too.

Here is a minimal example for testing:
[echo.py.txt](https://github.com/micropython/micropython/files/6067859/echo.py.txt)

- It works on a pyboard (pybv11-20210302-unstable-v1.14-82-gcdaec0dca)
- It works on the unix port (though with `sys.stdout` instead of `sys.stdout.buffer`)
- It fails on the pico (rp2-pico-20210301-unstable-v1.14-82-gcdaec0dca)

Output when it fails (`drain` never outputs anything):
```
# ready
.# input b'hello\r\n'
# drain
.........Traceback (most recent call last):
[...]
KeyboardInterrupt: 
```

And there is an exception when the `feedback_task` is not started, pressing RETURN twice results in:
```
# ready
# input b'hello\r\n'
# drain
Traceback (most recent call last):
  File "<stdin>", line 32, in <module>
  File "<stdin>", line 29, in echo
  File "uasyncio/core.py", line 1, in run_forever
  File "uasyncio/core.py", line 1, in run_until_complete
IndexError: empty heap
```

Compared to an output on the pyboard, where it echoes and goes back to reading as expected:
```
# ready
...# input b'hallo\r\n'
# drain
.hallo
# ready
[...]
```

**Comment by jonnor** [comment]
Is this still relevant in latest versions of MicroPython?
