### ISSUE TITLE
ESP32: network.PPP on UART not working, interrupt-issue?

### ISSUE THREAD

**Issue by Sebbb** [micropython/micropython#7021]
Hello,

I'm trying to use network.PPP with a GSM modem, but it does not work.

My code:

```
[.... initalization, APN setup etc.]

modem_uart.write('AT+CGDATA="PPP",1\r\n')
time.sleep(1)
print(modem_uart.readline())           => b'\r\n'
print(modem_uart.readline())           => b'CONNECT\r\n'
ppp = network.PPP(modem_uart)
ppp.active(True)
```

[waiting a few minutes, checking in the meantime
```
>>> ppp.ifconfig()
('0.0.0.0', '0.0.0.0', '255.255.255.255', '0.0.0.0')
>>> ppp.status()
>>> ppp.isconnected()
False

```
Then I checked if data is received from the modem, still in the rx buffer:
```
>>> modem_uart.any()
215

>>> modem_uart.read()
b'~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~~\xff}#\xc0!}!}!} }2}"}&} }*} } }#}$\xc0#}\'}"}(}"U\x83~\r\nNO CARRIER\r\n'
```

It seems the modem tries to establish connection, sending handshakes every few seconds, but network.PPP does not even pick up data from the UART. How is that supposed to work, I assumed it would be interrupt-driven in the background?

But I'm also not able to figure out how to get interrupts for received data on the UART manually, is it a feature missing on the ESP32, is that maybe causing the PPP issue?

```
>>> UART.irq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'UART' has no attribute 'irq'

>>> modem_uart.irq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'UART' object has no attribute 'irq'
```

I'm using esp32-idf4-20210202-v1.14.bin with a SIM800L GPRS modem.

According to https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/uart.html#uart-api-using-interrupts the ESP32 should support interrupts on the UART.

If interrupts are not supported and that is the issue, is there a way to manually feed the received data from the UART into ppp, from my main loop with select()?

Thanks
Sebastian

**Comment by Sebbb** [comment]
Update: was so easy.. I was missing ppp.connect()

```
>>> ppp.active(True)
>>> ppp.connect()
>>> print(ppp.ifconfig())
('10.167.232.52', '192.168.254.254', '255.255.255.255', '10.74.210.210')

```

That was not included in any of the examples I was able to find. Now it's working.

Closing the ticket :)
