### ISSUE TITLE
sdcard.py - OSError: timeout waiting for response

### ISSUE THREAD

**Issue by JurijOrlow** [micropython/micropython#7051]
I am using 8 GB microSD card, format FAT32. During mount code detects it as v2 card, but gives "OSError: timeout waiting for response". Tried to format as 4 GB FAT, did not work.

**Comment by sgbaird** [comment]
Any status update on this one? I'm also running into this issue on the Pico W using https://github.com/micropython/micropython/blob/v1.19.1/drivers/sdcard/sdcard.py (https://github.com/micropython/micropython/issues/8942). Mine is also formatted as FAT32 (Samsung 32 GB Evo Plus).

```python
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "/lib/sdcard/sdcard.py", line 59, in __init__
  File "/lib/sdcard/sdcard.py", line 93, in init_card
  File "/lib/sdcard/sdcard.py", line 152, in init_card_v2
OSError: timeout waiting for v2 card
```

**Comment by jonnor** [comment]
The linked thread seems to have a bunch of people who got their cards working. So check that for tips&tricks. And a few that did not =/
