### ISSUE TITLE
Out-of-bounds read in ff.c:create_name()

### ISSUE THREAD

**Issue by jepler** [micropython/micropython#7246]
While investigating diagnostics from the gcc address sanitizer, I ran across something that I think is a real out of bounds access.

```
==7314==ERROR: AddressSanitizer: global-buffer-overflow on address 0x555555c91347 at pc 0x555555bac2ed bp 0x7fffffffd3c0 sp 0x7fffffffd3b8
READ of size 1 at 0x555555c91347 thread T0
    #0 0x555555bac2ec in create_name ../../lib/oofatfs/ff.c:2824
    #1 0x555555bb110f in follow_path ../../lib/oofatfs/ff.c:3038
    #2 0x555555bbfc6b in f_mkdir ../../lib/oofatfs/ff.c:4737
    #3 0x555555b68ba2 in fat_vfs_mkdir ../../extmod/vfs_fat.c:250
    #4 0x555555a71df7 in fun_builtin_2_call ../../py/objfun.c:86
    #5 0x555555a37a4e in mp_call_function_n_kw ../../py/runtime.c:649
    #6 0x555555a38b5a in mp_call_method_n_kw ../../py/runtime.c:665
    #7 0x555555b5a1aa in mp_vfs_proxy_call ../../extmod/vfs.c:122
    #8 0x555555b5e369 in mp_vfs_mkdir ../../extmod/vfs.c:450
    #9 0x555555a7205f in fun_builtin_1_call ../../py/objfun.c:71
    #10 0x555555a37a4e in mp_call_function_n_kw ../../py/runtime.c:649
    #11 0x555555a38b5a in mp_call_method_n_kw ../../py/runtime.c:665
    #12 0x555555aed966 in mp_execute_bytecode ../../py/vm.c:1090
    #13 0x555555a70e67 in fun_bc_call ../../py/objfun.c:288
    #14 0x555555a37a4e in mp_call_function_n_kw ../../py/runtime.c:649
    #15 0x555555a3dbf1 in mp_call_function_0 ../../py/runtime.c:623
    #16 0x555555b8d52e in execute_from_lexer /home/jepler/src/micropython/ports/unix/main.c:145
    #17 0x555555b8d67a in do_file /home/jepler/src/micropython/ports/unix/main.c:293
    #18 0x555555b904dc in main_ /home/jepler/src/micropython/ports/unix/main.c:661
    #19 0x555555b90a3a in main /home/jepler/src/micropython/ports/unix/main.c:436
    #20 0x7ffff619a09a in __libc_start_main ../csu/libc-start.c:308
    #21 0x55555595fd69 in _start (/home/jepler/src/micropython/ports/unix/micropython-coverage+0x40bd69)

0x555555c91347 is located 0 bytes to the right of global variable '*.LC81' defined in '../../py/qstr.c' (0x555555c91340) of size 7
0x555555c91347 is located 57 bytes to the left of global variable '*.LC82' defined in '../../py/qstr.c' (0x555555c91380) of size 10
SUMMARY: AddressSanitizer: global-buffer-overflow ../../lib/oofatfs/ff.c:2824 in create_name
Shadow bytes around the buggy address:
  0x0aab2ab8a210: 00 04 f9 f9 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a220: 00 04 f9 f9 f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a230: 00 07 f9 f9 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a240: 00 01 f9 f9 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a250: 00 f9 f9 f9 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
=>0x0aab2ab8a260: 00 f9 f9 f9 f9 f9 f9 f9[07]f9 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a270: 00 02 f9 f9 f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a280: 00 04 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a290: 00 f9 f9 f9 f9 f9 f9 f9 00 02 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a2a0: 00 f9 f9 f9 f9 f9 f9 f9 00 02 f9 f9 f9 f9 f9 f9
  0x0aab2ab8a2b0: 00 06 f9 f9 f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7314==ABORTING
```

Here's the relevant bit of code:
```c
2812     /* Create LFN into LFN working buffer */
2813     p = *path; lfn = dp->obj.fs->lfnbuf; di = 0; 
2814     for (;;) {
2815         uc = tchar2uni(&p);         /* Get a character */
2816         if (uc == 0xFFFFFFFF) return FR_INVALID_NAME;       /* Invalid code or UTF decode error */
2817         if (uc >= 0x10000) lfn[di++] = (WCHAR)(uc >> 16);   /* Store high surrogate if needed */
2818         wc = (WCHAR)uc;
2819         if (wc < ' ' || wc == '/' || wc == '\\') break; /* Break if end of the path or a separator is found */
2820         if (wc < 0x80 && chk_chr("\"*:<>\?|\x7F", wc)) return FR_INVALID_NAME;  /* Reject illegal characters for LFN */
2821         if (di >= FF_MAX_LFN) return FR_INVALID_NAME;   /* Reject too long name */
2822         lfn[di++] = wc;                 /* Store the Unicode character */ 
2823     }   
2824     while (*p == '/' || *p == '\\') p++;    /* Skip duplicated separators if exist */
2825     *path = p;                          /* Return pointer to the next segment */
```

The problem exhibits itself when creating "dir", which happens to be a qstr (this problem occurs for heap strings but is probably not diagnosed since asan doesn't know about the structure of the micropython heap)

After a few iterations of the loop, line 2815 sets `uc=0` and advances `p` to point one byte past the string `'dir\0'`.  On line 2819, the loop is broken since `wc < ' '`, and execution jumps to 2824.  The dereference there is not valid, because it is one byte past the trailing `'\0'` of the string.

I am tempted to think that the `while` loop needs to be guarded by `if (wc)`: Ionly if the loop was exited due to encountering a slash or backslash do duplicated separators need to be skipped.  However, I'm not entirely confident of my diagnosis so I filed this as an issue rather than as a PR:
```
diff --git a/lib/oofatfs/ff.c b/lib/oofatfs/ff.c
index 0c9d04fe7..ffa119718 100644
--- a/lib/oofatfs/ff.c
+++ b/lib/oofatfs/ff.c
@@ -2821,7 +2821,9 @@ static FRESULT create_name (    /* FR_OK: successful, FR_INVALID_NAME: could not
         if (di >= FF_MAX_LFN) return FR_INVALID_NAME;   /* Reject too long name */
         lfn[di++] = wc;                 /* Store the Unicode character */
     }
-    while (*p == '/' || *p == '\\') p++;    /* Skip duplicated separators if exist */
+    if (wc) { // Either wc is 0 if the end of string is reached, or nonzero if a separator was encountered first
+        while (*p == '/' || *p == '\\') p++;    /* Skip duplicated separators if exist */
+    }
     *path = p;                          /* Return pointer to the next segment */
     cf = (wc < ' ') ? NS_LAST : 0;      /* Set last segment flag if end of the path */
 
```

**Comment by Josverl** [comment]
@jepler is this still relevant , and if so would it need to be labeled as 'Unicode' ?

**Comment by jepler** [comment]
It looks like this was fixed in #7248.

**Comment by jepler** [comment]
correction: it was fixed in [25fb6515663f7541704d15068de280702e428042](https://github.com/micropython/micropython/pull/11786)
