### ISSUE TITLE
`tuple + class MyTuple(tuple)` performs a wrong type cast

### ISSUE THREAD

**Issue by dimpolo** [micropython/micropython#7304]
```python
class MyTuple(tuple):
    pass

print((1,2) + MyTuple((3,4)))  # prints (1, 2, (nil))
```

Relevant code:
https://github.com/micropython/micropython/blob/3b950ed2959c603ff30dd6052c157e7981c4d2d6/py/objtuple.c#L145-L153
`mp_obj_tuple_binary_op` checks rhs with `mp_obj_is_subclass_fast` and then casts it to `mp_obj_tuple_t`

**Comment by peterhinch** [comment]
Subclassing built-in types is not fully supported: see [differences from CPython](https://github.com/micropython/micropython/wiki/Differences).

**Comment by dimpolo** [comment]
As far as I can tell, the pointer cast and subsequent memcopy (`mp_seq_cat`) are undefined behaviour.

**Comment by dimpolo** [comment]
```python
class MyTuple(tuple):
    pass

t = MyTuple((3,4))
t.field = 1
print((1,2) + t)  # crashes
```

**Comment by dimpolo** [comment]
This still reproduces.
See https://wokwi.com/projects/377113575387211777 for a `IllegalInstruction` crash

**Comment by peterhinch** [comment]
See [differences doc](https://github.com/micropython/micropython/wiki/Differences):
> Subclassing of builtin types is partially implemented, but there may be various differences and compatibility issues with CPython. [#401](https://github.com/micropython/micropython/issues/401)

**Comment by agatti** [comment]
Stack trace on current git master:

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
(1, 2, '', 
Program received signal SIGSEGV, Segmentation fault.
mp_obj_print_helper (print=print@entry=0x7fffffff9bb0, o_in=0x7ffff7a433e0, kind=kind@entry=PRINT_REPR) at ../../py/obj.c:128
128         if (MP_OBJ_TYPE_HAS_SLOT(type, print)) {
(gdb) print type
$1 = (const mp_obj_type_t *) 0x0
(gdb) bt
#0  mp_obj_print_helper (print=print@entry=0x7fffffff9bb0, o_in=0x7ffff7a433e0, kind=kind@entry=PRINT_REPR) at ../../py/obj.c:128
#1  0x00005555555a5822 in mp_obj_tuple_print (print=0x7fffffff9bb0, o_in=0x7ffff7a435a0, kind=PRINT_REPR) at ../../py/objtuple.c:53
#2  0x0000555555594dc3 in mp_obj_print_helper (print=print@entry=0x7fffffff9bb0, o_in=0x7ffff7a435a0, kind=kind@entry=PRINT_STR) at ../../py/obj.c:129
#3  0x00005555555abe85 in mp_builtin_print (n_args=1, pos_args=0x7fffffff9db0, kw_args=<optimized out>) at ../../py/modbuiltins.c:419
#4  0x000055555559acb8 in fun_builtin_var_call (self_in=0x555555646f80 <mp_builtin_print_obj>, n_args=1, n_kw=0, args=0x7fffffff9db0) at ../../py/objfun.c:118
#5  0x0000555555590afc in mp_call_function_n_kw (fun_in=0x555555646f80 <mp_builtin_print_obj>, n_args=1, n_kw=0, args=args@entry=0x7fffffff9db0) at ../../py/runtime.c:716
#6  0x00005555555aee07 in mp_execute_bytecode (code_state=code_state@entry=0x7fffffff9d80, inject_exc=inject_exc@entry=0x0) at ../../py/vm.c:984
#7  0x000055555559ae65 in fun_bc_call (self_in=0x7ffff7a432a0, n_args=0, n_kw=0, args=0x0) at ../../py/objfun.c:294
#8  0x0000555555590afc in mp_call_function_n_kw (fun_in=fun_in@entry=0x7ffff7a432a0, n_args=n_args@entry=0, n_kw=n_kw@entry=0, args=args@entry=0x0) at ../../py/runtime.c:716
#9  0x0000555555590b42 in mp_call_function_0 (fun=fun@entry=0x7ffff7a432a0) at ../../py/runtime.c:690
#10 0x00005555555fd77c in parse_compile_execute (source=<optimized out>, input_kind=input_kind@entry=MP_PARSE_FILE_INPUT, exec_flags=exec_flags@entry=32) at ../../shared/runtime/pyexec.c:137
#11 0x00005555555fdd1a in pyexec_file (filename=<optimized out>) at ../../shared/runtime/pyexec.c:737
#12 0x00005555555f9dbd in do_file (file=<optimized out>) at main.c:269
#13 0x00005555555fa42d in main_ (argc=argc@entry=2, argv=argv@entry=0x7fffffffa188) at main.c:692
#14 0x00005555555fa63c in main (argc=2, argv=0x7fffffffa188) at main.c:452
```

**Comment by jepler** [comment]
I was curious about the situation with lists. It's rejected with a type error...

```
>>> class L(list): pass
... 
>>> [1,2] + L((3,4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __add__: 'list', 'list'
```
