### ISSUE TITLE
esp32: CMake error on macOS

### ISSUE THREAD

**Issue by mdaeron** [micropython/micropython#7345]
I'm trying to follow the instructions in [esp32/README.md](https://github.com/micropython/micropython/blob/master/ports/esp32/README.md) to the letter. I'm on macOS Catalina (10.15.7), with CMake v 3.20.2.

When running the following script:

````bash
export HERE=$(pwd)

git clone https://github.com/micropython/micropython.git
git clone -b v4.2 --recursive https://github.com/espressif/esp-idf.git

cd $HERE/esp-idf
./install.sh
source ./export.sh

cd $HERE/micropython
make -C mpy-cross

cd $HERE/micropython/ports/esp32
make submodules

cd $HERE/micropython/ports/esp32
make
````

I get the following error(s):

````bash
...
[100%] Built target __idf_main
[100%] Generating ld/esp32.project.ld
Traceback (most recent call last):
  File "/Users/mathieu/ShareBox/μPy/firmware/tinypico+ulab+i2s/micropython/esp-idf/tools/ldgen/generation.py", line 592, in add_sections_info
    results = parser.parseString(first_line)
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 1814, in parseString
    raise exc
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 1804, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 3722, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 1552, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 3472, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of line (at char 35), (line:1, col:36)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mathieu/ShareBox/μPy/firmware/tinypico+ulab+i2s/micropython/esp-idf/tools/ldgen/ldgen.py", line 158, in <module>
    main()
  File "/Users/mathieu/ShareBox/μPy/firmware/tinypico+ulab+i2s/micropython/esp-idf/tools/ldgen/ldgen.py", line 116, in main
    sections_infos.add_sections_info(dump)
  File "/Users/mathieu/ShareBox/μPy/firmware/tinypico+ulab+i2s/micropython/esp-idf/tools/ldgen/generation.py", line 594, in add_sections_info
    raise ParseException("Parsing sections info for library " + sections_info_dump.name + " failed. " + p.message)
  File "/Users/mathieu/.espressif/python_env/idf4.2_py3.7_env/lib/python3.7/site-packages/pyparsing.py", line 272, in __getattr__
    raise AttributeError(aname)
AttributeError: message
make[3]: *** [esp-idf/esp32/ld/esp32.project.ld] Error 1
make[2]: *** [esp-idf/esp32/CMakeFiles/__ldgen_output_esp32.project.ld.dir/all] Error 2
make[1]: *** [all] Error 2
make failed with exit code 2
make: *** [all] Error 2
````

I'm not sure where to start looking for the root of the problem?

**Comment by mdaeron** [comment]
Follow-up for anyone with a similar problem: the issue has to do with the presence of unicode characters in the path. After moving the script to another location, everything seems to work fine.
