### ISSUE TITLE
mpremote: Use time delay between copying files in WINDOWS batch file

### ISSUE THREAD

**Issue by IhorNehrutsa** [micropython/micropython#7417]
I use WINDOWS 10 and ESP32 
```
python.exe mpremote.py connect port:COM8 cp file1.py :
timeout 2
python.exe mpremote.py connect port:COM8 cp file2.py :
timeout 2
python.exe mpremote.py connect port:COM8 cp file3.py :
```
If timeout less 2 then raise "could not enter raw repl"
```
b'MicroPython v1.15-274-g023342b45-dirty on 2021-06-11; ESP32 module with ESP32\r\nType "help()" for more information.\r\n>>> '
Traceback (most recent call last):
  File "d:\MicroPython\micropython_0\tools\mpremote\mpremote.py", line 6, in <module>
    sys.exit(main.main())
  File "d:\MicroPython\micropython_0\tools\mpremote\mpremote\main.py", line 408, in main
    pyb.enter_raw_repl()
  File "d:\MicroPython\micropython_0\tools\mpremote\mpremote/../..\pyboard.py", line 340, in enter_raw_repl
    raise PyboardError("could not enter raw repl")
pyboard.PyboardError: could not enter raw repl
```

**Comment by dpgeorge** [comment]
This is probably fixed by 5a86d8dc424b5923d5d1a7c1352378ef328847d6.  Please reopen if not.
