### ISSUE TITLE
Issue with 'lib/memzip/make-memzip.py'

### ISSUE THREAD

**Issue by gvanem** [micropython/micropython#7522]
I tried this script when experimenting creating a .zip-file for the Python standard-lib files.
First error was using this with CPython 3.6 was:
```python
  adding: __future__/setup.py (160 bytes security) (stored 0%)
  adding: __future__/__future__.py (160 bytes security) (stored 0%)
Traceback (most recent call last):
  File "F:\MingW32\src\Languages\MicroPython\lib\memzip\make-memzip.py", line 78, in <module>
    main()
  File "F:\MingW32\src\Languages\MicroPython\lib\memzip\make-memzip.py", line 75, in main
    create_c_from_file(args.c_filename, args.zip_filename)
  File "F:\MingW32\src\Languages\MicroPython\lib\memzip\make-memzip.py", line 30, in create_c_from_file
    print('#include <stdint.h>', file=c_file)
TypeError: a bytes-like object is required, not 'str'
```
Which I fixed by simply:
```diff
--- a/lib/memzip/make-memzip.py 2020-09-20 12:29:44
+++ b/lib/memzip/make-memzip.py 2021-07-11 12:09:44
@@ -26,7 +26,7 @@

 def create_c_from_file(c_filename, zip_filename):
     with open(zip_filename, 'rb') as zip_file:
-        with open(c_filename, 'wb') as c_file:
+        with open(c_filename, 'w') as c_file:
             print('#include <stdint.h>', file=c_file)
```
(no reason for a .c-file to be binary. `"wt"` is implied in CPython3.x on Windows, right?)

Then the second error:
```python
Traceback (most recent call last):
  File "F:\MingW32\src\Languages\MicroPython\lib\memzip\make-memzip.py", line 78, in <module>
    main()
  File "F:\MingW32\src\Languages\MicroPython\lib\memzip\make-memzip.py", line 75, in main
    create_c_from_file(args.c_filename, args.zip_filename)
  File "F:\MingW32\src\Languages\MicroPython\lib\memzip\make-memzip.py", line 39, in create_c_from_file
    if type(byte) is types.StringType:
AttributeError: module 'types' has no attribute 'StringType'
```

Which I fixed by simply removing this `if ` test:
```diff
--- a/lib/memzip/make-memzip.py 2020-09-20 12:29:44
+++ b/lib/memzip/make-memzip.py 2021-07-11 12:19:39
@@ -36,9 +36,6 @@
                     break
                 print('   ', end='', file=c_file)
                 for byte in buf:
-                    if type(byte) is types.StringType:
-                        print(' 0x{:02x},'.format(ord(byte)), end='', file=c_file)
-                    else:
                         print(' 0x{:02x},'.format(byte), end='', file=c_file)
```

**Comment by jonnor** [comment]
Is this still relevant for recent MicroPython?

**Comment by dpgeorge** [comment]
Yes, I think it's still relevant, the file has just moved to `shared/memzip/make-memzip.py`.
