### ISSUE TITLE
ESP32 - cannot initialize WLAN

### ISSUE THREAD

**Issue by eliclement** [micropython/micropython#7904]
While initializing a WLAN (on an ESP32 GENERIC_SPIRAM board) with:
```
>>> import network
>>> station = network.WLAN(network.STA_IF)
```
the following error occurs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Wifi Unknown Error 0x0101
```

MicroPython version used (build with ESP-IDF (stable) 4.3.1):
```
>>> import sys
>>> sys.implementation
(name='micropython', version=(1, 17, 0), mpy=10757)
```

**Comment by HughMaingauche** [comment]
I could reproduce this error
```
>>> import network
>>> sta_if = network.WLAN(network.STA_IF)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Wifi Unknown Error 0x0101
```

MP version used (build with ESP-IDF v5.0-dev-489-gef98a363e3 - master -)

```
>>> import sys
>>> sys.implementation
(name='micropython', version=(1, 17, 0), mpy=10757)
```

**Comment by xlla** [comment]
same issue here while work with lv_micropython

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 7, in do_connect
RuntimeError: Wifi Unknown Error 0x0101

**Comment by PWSJA** [comment]
I got the same error while using lv_micropython and wifi. I think it is caused by too less (DMA-)RAM. Namely, I fixed it by changing the parameters factor and double_buffer in the initialization to 32 and False:
```py
ili9488(factor=32, double_buffer=False)
```
After doing that, the error disappeared.

**Comment by Chleba** [comment]
The same error even now - v1.19.1 MicroPython using ESP32S3.
When I'm trying to create WiFi STA_IF I get an unknown error.
I did tried using esp-idf v4.4 and v5.x> and still no fix.

**Comment by PWSJA** [comment]
Have you tried to enhance the factor and to set double_buffer to False?

**Comment by Chleba** [comment]
I did not, but I've tried to go through the steps that are described here - https://github.com/micropython/micropython/discussions/10359, and everything is working now.

**Comment by mattytrentini** [comment]
This error - "Wifi Unknown Error 0x0101" - will occur when initialising `network.WLAN` if you have _misconfigured flash for your board_. 

In my particular case, soft-resetting with Ctrl+D would show:

```bash
>>> [Ctrl+D]
MPY: soft reboot
Traceback (most recent call last):
  File "_boot.py", line 11, in <module>
  File "inisetup.py", line 34, in setup
  File "inisetup.py", line 7, in check_bootsec
OSError: (-24579, 'ESP_ERR_FLASH_NOT_INITIALISED')
```

Which was because I was trying to use firmware that expeted 8MB of flash when the board only had 4MB. But trying to init WLAN would also produce the error - I'd guess that the IDF is trying to read or write something to flash when the network starts.

In any case, if you see this error, check to ensure that your flash is configured correctly!

**Comment by ChrisJones79** [comment]
How do you configure your flash? I have the same problem but other than just flashing the board with ESP32S3 GENERIC OCTAL(GENERIC_S3_SPIRAM_OCT-20230329-unstable-v1.19.1-993-g283c1ba07), I don't see where I would configure anything. How are you guys doing the actual configuration?

**Comment by chk-jxcn** [comment]
met the same issue on lv_micropython 1.19, the error code 0x0101 means malloc memory fail.
modify the heap size of micropython to a smaller value could resolve it.

**Comment by intx82** [comment]
Guys, i have the same error and in my case it's related to enabled Bluetooth, if i disable Bluetooth, Wi-Fi connects and works well. 

`MicroPython v1.21.0 on 2023-10-06; ESP32C3 module with ESP32C3`

**Comment by ChrisJones79** [comment]
> This error - "Wifi Unknown Error 0x0101" - will occur when initialising `network.WLAN` if you have _misconfigured flash for your board_.
> 
> In my particular case, soft-resetting with Ctrl+D would show:
> 
> ```shell
> >>> [Ctrl+D]
> MPY: soft reboot
> Traceback (most recent call last):
>   File "_boot.py", line 11, in <module>
>   File "inisetup.py", line 34, in setup
>   File "inisetup.py", line 7, in check_bootsec
> OSError: (-24579, 'ESP_ERR_FLASH_NOT_INITIALISED')
> ```
> 
> Which was because I was trying to use firmware that expeted 8MB of flash when the board only had 4MB. But trying to init WLAN would also produce the error - I'd guess that the IDF is trying to read or write something to flash when the network starts.
> 
> In any case, if you see this error, check to ensure that your flash is configured correctly!

Could you please give me the overview of what you mean by configuring flash? Are you talking about creating a custom build? Creating a certain module?

**Comment by AmirHmZz** [comment]
Got error with `micropython1.22.1` on `ESP32`. Flash seems to be ok and error solves after some hard reboots.

**Comment by suecher** [comment]
> Guys, i have the same error and in my case it's related to enabled Bluetooth, if i disable Bluetooth, Wi-Fi connects and works well.
> 
> `MicroPython v1.21.0 on 2023-10-06; ESP32C3 module with ESP32C3`

I also encountered the same problem, which will appear when using Bluetooth. Did you solve it finally?

**Comment by suecher** [comment]
> Guys, i have the same error and in my case it's related to enabled Bluetooth, if i disable Bluetooth, Wi-Fi connects and works well.
> 
> `MicroPython v1.21.0 on 2023-10-06; ESP32C3 module with ESP32C3`

@intx82 
I also encountered the same problem, which will appear when using Bluetooth. Did you solve it finally?

**Comment by jamesdeluk** [comment]
Same issue.

Chip: https://www.waveshare.com/wiki/ESP32-S3-Zero

Firmwares tried: 1.24.1, 1.24.1 4MiB, and 1.25.0-preview.539

**Comment by projectgus** [comment]
> Same issue.
> 
> Chip: https://www.waveshare.com/wiki/ESP32-S3-Zero
> 
> Firmwares tried: 1.24.1, 1.24.1 4MiB, and 1.25.0-preview.539

Hi @jamesdeluk, Can you please post the code you're running to reproduce the error, and the full output from MicroPython? I think there are a few issues mixed up in the comments here, but in general Wi-Fi on ESP32-S3 should work on all three of these versions.
