### ISSUE TITLE
ports/unix: uasyncio.ThreadSafeFlag appears broken

### ISSUE THREAD

**Issue by crzcrz** [micropython/micropython#7965]
The minimal program to reproduce the issue:

```python
import uasyncio as asyncio

f = asyncio.ThreadSafeFlag()

async def main():
    await f.wait()

asyncio.run(main())
```

The result:

```
Traceback (most recent call last):
  File "t.py", line 8, in <module>
  File "/usr/lib/micropython/uasyncio/core.py", line 222, in run
  File "/usr/lib/micropython/uasyncio/core.py", line 191, in run_until_complete
  File "/usr/lib/micropython/uasyncio/core.py", line 176, in run_until_complete
  File "t.py", line 6, in main
  File "/usr/lib/micropython/uasyncio/event.py", line 57, in wait
  File "/usr/lib/micropython/uasyncio/core.py", line 94, in queue_read
  File "/usr/lib/micropython/uasyncio/core.py", line 79, in _enqueue
TypeError: can't convert NoneType to int
```

I poked around it a bit, and the flow to the failure is as follows:

https://github.com/micropython/micropython/blob/cb99ca9862827f57c370555841810e98701ecfa2/extmod/uasyncio/core.py#L79

https://github.com/micropython/micropython/blob/cb99ca9862827f57c370555841810e98701ecfa2/ports/unix/moduselect.c#L88

https://github.com/micropython/micropython/blob/cb99ca9862827f57c370555841810e98701ecfa2/ports/unix/moduselect.c#L76

This ends up in `ThreadSafeFlag.ioctl()`, which returns None for any request other than `MP_STREAM_POLL` and causes the exception above.

https://github.com/micropython/micropython/blob/cb99ca9862827f57c370555841810e98701ecfa2/extmod/uasyncio/event.py#L47-L50

**Comment by jimmo** [comment]
On everything-except-unix, we use a built-in implementation of select() (in extmod/moduselect.c), which knows how to poll Python objects implementing the stream protocol. However, on Unix it uses the "native" (i.e. posix) select, which only knows about file descriptors (hence why None can't be converted to int).

The correct fix is to make the Unix select implementation also support Python objects (i.e. a hybrid of `extmod/moduselect.c` and `ports/unix/moduselect.c`), but in the meantime you can build the Unix port with the built-in select implementation instead by adding the following to mpconfigport.h (or mpconfigvariant.h).

```
#define MICROPY_PY_USELECT_POSIX (0)
#define MICROPY_PY_USELECT (1)
```

I have a variant that I use for BLE testing and aioble development that sets this.

I've wondered about proposing to make this the default for the unix port... (generally my view is that the default unix port should mirror the bare-metal port, and a "more CPython like" build can be enabled via a variant) but other use cases depend on the posix behavior so this would be a breaking change.

Longer term we plan to improve uasyncio's event-waiting (see https://github.com/micropython/micropython/pull/6125 and linked PRs) this will work the same across the different ports.

In the meantime, it's probably an oversight that https://docs.micropython.org/en/latest/library/uasyncio.html#class-threadsafeflag doesn't mention this behavior.

**Comment by agatti** [comment]
This doesn't seem to occur anymore on current git master.  Marking as proposed-close for the time being.

**Comment by dpgeorge** [comment]
The hybrid select approach was implemented in ef71028f77e4a6fc449c64906ebad0a160f35240, so this issue is fixed.
