### ISSUE TITLE
ESP32S3 with SPIRAM, Failure to Mount SD Card

### ISSUE THREAD

**Issue by TGiles1998** [micropython/micropython#8121]
Hi,

Looking at the default slot 1 to mount the SD card:

SCK = 36,
MOSI = 35,
MISO = 37,
CS = 34,

The CS is not broken out to a GPIO pin and is also used as the CS for external RAM.

I tried to reassign the CS pin:

sd = machine.SDCard(slot=1, cs=5)

and mount it:

os.mount(sd, "/sd")

but produces the error:

E (55849) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 16

Any help would be great thanks!

**Comment by TGiles1998** [comment]
Using slot 3 produces the error:

>>> os.mount(SDCard(slot=3), "/sd")
E (58945) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
E (58945) sdspi_host: spi_bus_initialize failed with rc=0x102
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: (-258, 'ESP_ERR_INVALID_ARG')

**Comment by TGiles1998** [comment]
Can't mount slot 2 either

os.mount(SDCard(slot=2), "/sd") 
E (183635) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
E (183635) sdspi_host: spi_bus_initialize failed with rc=0x102
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: (-258, 'ESP_ERR_INVALID_ARG')

**Comment by TGiles1998** [comment]
import os
print("Importing OS")
import machine
print("Importing Machine")
from machine import Pin
print("Importing Pin, from Machine")
from machine import SPI
print("Importing SPI, from Machine")
from machine import SoftSPI
print("Importing SoftSPI, from Machine")
from machine import SDCard
print("Importing SDCard, from Machine")

sd = machine.SDCard(width=1, sck=Pin(12), mosi=Pin(11), miso=Pin(13), cs=Pin(10)) # didn't break with this 
print("Acquiring Software SPI Port")
os.mount(sd, '/sd') # Breaks Here <------------
print("Mounting the sd card under /sd")


E (14873) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107

**Comment by TGiles1998** [comment]
sck = machine.Pin(12)
miso = machine.Pin(13)
mosi = machine.Pin(11)
cs = machine.Pin(10)
sd = machine.SDCard(slot=1, sck=sck, miso=miso, mosi=mosi, cs=cs)
os.mount(sd, '/sd')

Still won't work

Errors:

E (176293) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 16

>>> sd = machine.SDCard(slot=2, sck=sck, miso=miso, mosi=mosi, cs=cs)
E (149993) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
E (149993) sdspi_host: spi_bus_initialize failed with rc=0x102
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: (-258, 'ESP_ERR_INVALID_ARG')

**Comment by TGiles1998** [comment]
Solved in https://github.com/micropython/micropython/issues/8217#issuecomment-1067425919
