### ISSUE TITLE
urequests.get() error related to getaddrinfo

### ISSUE THREAD

**Issue by rafaelaroca** [micropython/micropython#8298]
Hello:

I just compiled MicroPython for RPI Pico with WIZNET5k support as described here: https://github.com/Wiznet/RP2040-HAT-MicroPython

Ethernet connects and works. 

However urequests gives this error:

request = urequests.get('http://bipes.net.br/test.txt')
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "urequests.py", line 116, in get
  File "urequests.py", line 55, in request
TypeError: function takes 2 positional arguments but 4 were given

I checked urequests.py and the implementation is:
ai = usocket.getaddrinfo(host, port, 0, usocket.SOCK_STREAM)

If I change this line to 
ai = usocket.getaddrinfo(host, port)

The problem is solved and urequests.get() works!

However, I am uncertain if this would cause other boards/implementations problems.

Can this fix be applied to urequests.py, or it could break other network implementations?

thanks

**Comment by dpgeorge** [comment]
This issue should have been fixed by 9438fb7321f1f0fb9faae666808e86d7f47b8619
