### ISSUE TITLE
ESP32: os.listdir with non-ASCII chars

### ISSUE THREAD

**Issue by Narsskrarc** [micropython/micropython#8300]
Hi,

I have a file on the SD-Card names "Frühstück.wav". With `os.listdir` it is displayed as "Frhstck.wav", When I convert it to `bytes()` I can see it is b"Fr\x81hst\x81ck.wav" in fact.

I have to compare the name to a string named "Frühstück.wav". But I can't convert neither the string from os.listdir in unicode nor can I create a string which is equal to the string from os.listdir.
I found the hint to use a unicode directory for os.listdir(). I tried to decode(anything) the b"...", but it throws an UnicodeError no matter which encoding I try. The other way round I can encode the unicode string with any encoding, it gets the same byte string:
`"Frühstück.wav".encode('UTF-8') -> b'Fr\xc3\xbchst\xc3\xbcck.wav'`
`"Frühstück.wav".encode('ASCII') -> b'Fr\xc3\xbchst\xc3\xbcck.wav'`
`"Frühstück.wav".encode('ISO-8859-1') -> b'Fr\xc3\xbchst\xc3\xbcck.wav'`

What is the right way to handle non-ascii-filenames with micropython?

**Comment by m-u-xyz** [comment]
Possibly-related problem:

```
>>> os.listdir("/lib")
['mpdb.py', 'support', 'app', 'moat']
>>> os.listdir("/lib/app")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeError:
>>> d=os.listdir("/lib/app")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeError:
```

… now what do I do, other than re-initialize the file system?

**Comment by Josverl** [comment]
I have a PR brewing that should fix this, and other Unicode issues.

@smurfix:  there are the [two unicode PRs](https://github.com/micropython/micropython/pulls?q=is%3Aopen+is%3Apr+label%3Aunicode) 

Note I have also seen issues that indicate  that a vfs corruption can surface as a UnicodeError>
If that is the case it would be interesting to understand / research why. Possibly by copying the possibly corrupted flash/SD to a .bin file for closer inspection.

**Comment by m-u-xyz** [comment]
Yeah, in my case it's definitely a file system corruption. But as it's a FAT partition for some reason (shouldn't the default be LFS2??) I decided to reformat it as LFS instead of trying to figure out what could possibly have gone wrong.

**Comment by Josverl** [comment]
> in my case it's definitely a file system corruption. But as it's a FAT partition for some reason

Which port/board was this on, in your case?

It may be worthwhile to try to reproduce this to understand why a Unicode error is raised rather than some OsError / file error

**Comment by m-u-xyz** [comment]
The board is a TinyPico (ESP32-S3). There might have been some multithreading and/or watchdog signalling involved. Thus, given that FAT is very far from being a resilient file system, I don't think analyzing this further is worth the effort. Besides, the image is gone now. :-/

Reproducing the exception is simple enough. Set up a FAT file system in RAM, create a file named "test" on it, find the directory entry and replace the "e" with a 0xC0 byte.

**Comment by Josverl** [comment]
Thanks - found the same possible issue across all vfs-es - working on a fix to raise an OSError instead, but could also try to convert to utf-8 with a error='replace' , at the risk of silent data corruption. OK-ish for a file-name - not so ok for file contents.

**Comment by m-u-xyz** [comment]
File contents are OK to raise annoying exceptions when it's not UTF-8. That's what binary mode is for.

My problem with error="replace" is that it's not reversible, thus I still can't delete that file. The "surrogateescape" method (using `U+DC80..U+DCFF` to represent non-UTF8-ish bytes; see also https://peps.python.org/pep-0383/) would be more helpful.

**Comment by Josverl** [comment]
> The \"surrogateescape\" method (using U+DC80..U+DCFF to represent non-UTF8-ish bytes;

Not sure if that weighes up to the (non-optimised) increase : 
Size impact: +712 bytes on top of ignore+replace handlers (total +1,048 bytes for all three)

**Comment by m-u-xyz** [comment]
>  Size impact: +712 bytes on top of ignore+replace handlers (total +1,048 bytes for all three)

That should probably behind a "NON_UTF8_FILENAMES" feature flag. (Or however else we'd name it.)

**Comment by sosi-deadeye** [comment]
Once I had this issue even on Linux. I didn't know that it's possible, but it seems there is nothing to protect the VFS against broken UTF8 encoding.

**Comment by m-u-xyz** [comment]
You're correct -- file names are a sequence of bytes, and most file systems don't care about their meaning. The only forbidden values are null and slash.

There still are legacy file systems with non-UTF8 filenames out there.

**Comment by Josverl** [comment]
In Windows filenames are explicitly text/utf , not bytes since NTFS / Windows NT some 30 years ago. 
But the fix could work for all filesystems, except ROMFS perhaps.

**Comment by Josverl** [comment]
@Narsskrarc,

A unicode Pr has been merged that includes a fix for this issue. 

This is using latest preview

```
>>> import os
>>> os.listdir()
['Fr\xfchst\xfcck.wav']
>>> print(os.listdir()[0])
Frühstück.wav
```

Please do feel free to re-open if needed.
