### ISSUE TITLE
pip-micropython can't install micropython-select on some systems

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#839]
Running:

    pip-micropython install micropython-select

Does not work (for me).  It's downloading the correct package and using CPython to run the setup.py script.  But then this script eventually imports select which imports the micropython-select not the CPython select.  The micropython-select imports ffi which doesn't exist in CPython.

Here is the error message:
```
Destination library directory: /home/damien/.micropython/lib
Downloading/unpacking micropython-select
  Downloading micropython-select-0.0.8.tar.gz
  Running setup.py (path:/tmp/pip-micropy-venv/build/micropython-select/setup.py) egg_info for package micropython-select
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/tmp/pip-micropy-venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/tmp/pip-micropy-venv/lib/python3.4/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-micropy-venv/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>
        from setuptools.compat import numeric_types, basestring
      File "/tmp/pip-micropy-venv/lib/python3.4/site-packages/setuptools/compat.py", line 49, in <module>
        from http.server import HTTPServer, SimpleHTTPRequestHandler
      File "/usr/lib64/python3.4/http/server.py", line 93, in <module>
        import select
      File "/tmp/pip-micropy-venv/build/micropython-select/select.py", line 1, in <module>
        import ffi
    ImportError: No module named 'ffi'
```

**Comment by pfalcon** [comment]
Ok, it was discussed as an approach, now there's explicit ticket to create self-hosted package manager for uPy, which also will take care of this issue - https://github.com/micropython/micropython-lib/issues/19

**Comment by dpgeorge** [comment]
This issue is resolved now that we have upip.  Specifically the following works:
```
micropython -m upip install micropython-select
```
