### ISSUE TITLE
mpy-cross in recent commits, esp32 build failure

### ISSUE THREAD

**Issue by stephanelsmith** [micropython/micropython#8474]
On esp32 build, esp-idf v4.4, the issue is a firmware build issue after making mpy-cross.  Possibly a contributing factor to kwargs issue: https://github.com/micropython/micropython/issues/8473
(hoping this issue will be resolved with this resolved)

Make mpy-cross itself does not have an error.  It's when I actually build the firmware.  Last working commit where I can make mpy-cross and then build firmware without errors is bf3585b33.

ERROR 2e3f2045f (HEAD -> master, origin/master, origin/HEAD) py/runtime: Use size_t/ssize_t instead of uint/int.
.....
ERROR bb7087411 py/vm: Prevent array bound warning when using -MP_OBJ_ITER_BUF_NSLOTS.
ERROR 7e8222ae0 py/emitnative: Don't store prelude at end of machine code if not needed.
GOOD  bf3585b33 py/asmxtensa: Fix use of l32i/s32i when offset won't fit in encoding.

Process is simply:
make -C mpy-cross
from root micropython directory, then make a clean firmware build.  From commit 7e8222ae0, I see the following error:
```
Traceback (most recent call last):
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 1609, in <module>
    main()
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 1584, in main
    compiled_modules = [read_mpy(file) for file in args.files]
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 1584, in <listcomp>
    compiled_modules = [read_mpy(file) for file in args.files]
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 1262, in read_mpy
    raw_code = read_raw_code(reader, cm_escaped_name, qstr_table, obj_table, segments)
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 1215, in read_raw_code
    read_raw_code(reader, cm_escaped_name, qstr_table, obj_table, segments)
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 1191, in read_raw_code
    rc = RawCodeNative(
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 913, in __init__
    super(RawCodeNative, self).__init__(
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 735, in __init__
    ) = extract_prelude(self.fun_data, prelude_offset)
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 423, in extract_prelude
    ) = read_prelude_sig(local_read_byte)
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 371, in read_prelude_sig
    z = read_byte()
  File "/home/ssmith/micropython/tools/mpy-tool.py", line 411, in local_read_byte
    b = bytecode[ip_ref[0]]
IndexError: index out of range
```

**Comment by dpgeorge** [comment]
Thanks for the report, I can confirm the issue.  There needs to be `@micropython.native` code frozen into the esp32 port to see it though (which is why CI did not pick it up).

**Comment by dpgeorge** [comment]
See #8477 for a fix.

**Comment by dpgeorge** [comment]
The offending commit was reverted in b8d959d6cf6afab4277a7e094be5107f27105b17.  A test was added in be25e333dfff076f631e50fd5eec2fa626b2625b which freezes native code as part of an esp32 build.
