### ISSUE TITLE
In esp32-s3, cannot use (machine. Sdcard class)

### ISSUE THREAD

**Issue by lyzp** [micropython/micropython#8514]
Call machine.Sdcard (slot = 2, miso = pin (36), MoSi = pin (35), SCK = pin (37), CS = pin (38)) on espressif esp32-s3 development board reports an error:

_[0;31mE (8250) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
[0;31mE (8250) sdspi_host: spi_bus_initialize failed with rc=0x102
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
OSError: (-258, 'ESP_ERR_INVALID_ARG')_

modify  micropython/ports/esp32/machine_sdcard.c  Line 214，machine.sdcard() call can be resumed
_.dma_channel = 2----------->.dma_channel = 3_

Because in ESP-IDF dma_channel==3 Indicates automatic assignment DMA,Otherwise, the machine.Sdcard() will not work properly

**Comment by jonnor** [comment]
So it seems that the machine.SDCard() constructor on ESP32 port needs to allow to specify a dma_channel parameters. That way users can set this to 3 on ESP32-S3?
