### ISSUE TITLE
machine.RTC.datetime broken on Raspberry Pi Pico

### ISSUE THREAD

**Issue by evilhamsterman** [micropython/micropython#9667]
Disregarding all the other issues with the RTC library in MicroPython, it appears it is completely broken in the current version on Raspberry Pi Pico. Whenever trying to set the time using machine.RTC.datetime passing a tuple returns an error that argument is the wrong type, same thing with a list. And calling the function without an argument says its missing 1 required argument instead of returning a tuple.

```python
MPY: soft reboot
MicroPython v1.19.1 on 2022-10-14; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> import machine
>>> rtc=machine.RTC.datetime((2022,10,17,0,21,33,0,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument has wrong type
>>> rtc=machine.RTC
>>> rtc.datetime((2022,10,17,0,21,33,0,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument has wrong type
>>> rtc.datetime()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function missing 1 required positional arguments
>>> 
```

**Comment by evilhamsterman** [comment]
Nevermind I didn't initialize the class correctly with `rtc=machine.RTC()` I missed the ()
